#+TITLE: Emacs configuration
#+AUTHOR: Steffen Fiedler

* Installation
** Personal
#+BEGIN_SRC emacs-lisp
  (load (concat user-emacs-directory "secrets.el"))
  (setq user-full-name full-name
        user-mail-address email-address)
#+END_SRC
** Package archives
#+BEGIN_SRC emacs-lisp
  (require 'package)
  (setq package-enable-at-startup nil)
  (setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                           ("melpa-stable" . "http://stable.melpa.org/packages/")
                           ("melpa" . "http://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")))

  (setq package-archive-priorities '(("melpa-stable" . 50)
                                     ("gnu" . 10)
                                     ("marmalade" . 10)
                                     ("melpa" . 0)))
  (unless package--initialized (package-initialize t))
  ;; bootstrap use-package (http://www.lunaryorn.com/)
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  ;; and call it?
  (eval-when-compile (require 'use-package))
  (when (not package-archive-contents)
    (package-refresh-contents))
#+END_SRC
** Package update
Keep installed packages updated and remove old versions.
#+BEGIN_SRC emacs-lisp
  ;; (use-package auto-package-update
  ;;   :config
  ;;   (setq auto-package-update-delete-old-versions t)
  ;;   (setq auto-package-update-hide-results t)
  ;;   (auto-package-update-maybe))
#+END_SRC
* Sane defaults
** Hide warnings
*** Package cl is deprecated
Emacs > 27 displays warning when `cl` is required. (see [issue](https://github.com/kiwanami/emacs-epc/issues/35))
#+BEGIN_SRC emacs-lisp
  (setq byte-compile-warnings '(cl-functions))
#+END_SRC
** Default directory
Defines user root as default directory.
#+BEGIN_SRC emacs-lisp
  (setq default-directory "~/")
#+END_SRC
** ZSH configuration
https://github.com/Wilfred/ag.el/issues/93
#+BEGIN_SRC emacs-lisp
  (setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin"))
#+END_SRC
** Auto revert
When something changes a file, automatically refresh the buffer containing that file so they can’t get out of sync.
#+BEGIN_SRC emacs-lisp
  (global-auto-revert-mode t)
#+END_SRC
** Regions

#+BEGIN_SRC emacs-lisp
  ;; These functions are useful. Activate them.
  (put 'downcase-region 'disabled nil)
  (put 'upcase-region 'disabled nil)
  (put 'narrow-to-region 'disabled nil)
#+END_SRC

** dired

#+BEGIN_SRC emacs-lisp
  (put 'dired-find-alternate-file 'disabled nil)
#+END_SRC

** Stop creating backup files
Save and commit often instead of relying on emacs' automatic backup~ files.
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
#+END_SRC
And disable emacs' #auto-save# files.
#+BEGIN_SRC emacs-lisp
  (setq auto-save-default nil)
#+END_SRC

** UTF-8 everywhere

#+BEGIN_SRC emacs-lisp
  (setq locale-coding-system 'utf-8) ; pretty
  (set-terminal-coding-system 'utf-8) ; pretty
  (set-keyboard-coding-system 'utf-8) ; pretty
  (set-selection-coding-system 'utf-8) ; please
  (prefer-coding-system 'utf-8) ; with sugar on top
  (setq slime-net-coding-system 'utf-8-unix)
#+END_SRC

** Indentation and tabs
Make indentation commands use space only, never tab characters
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC
Set default tab char's display width to 4 spaces.
#+BEGIN_SRC emacs-lisp
  (setq-default tab-width 4)
#+END_SRC

** 'y' or 'n' short handles will do
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Replace selected with any kind of input
#+BEGIN_SRC emacs-lisp
  (delete-selection-mode 1)
#+END_SRC
** Enable systems clipboard manager interactions
#+BEGIN_SRC emacs-lisp
  (setq x-select-enable-clipboard t
        x-select-enable-primary t)
#+END_SRC
** Stop 'donking
No negative speaker feedback.
#+BEGIN_SRC emacs-lisp
  (setq visible-bell t)
#+END_SRC
** Adaptive cursor width
Make the cursor the full width of the character it is under – e.g. the full width of a TAB character (from [[http://pragmaticemacs.com/emacs/adaptive-cursor-width/][pragmatic emacs]]).
#+BEGIN_SRC emacs-lisp
  (setq x-stretch-cursor t)
#+END_SRC
* Mac defaults
#+BEGIN_SRC emacs-lisp
  (when (string-equal system-type "darwin")
    ;; Non-native fullscreen
    (setq ns-use-native-fullscreen nil)
    ;; delete files by moving them to the trash
    (setq delete-by-moving-to-trash t)
    (setq trash-directory "~/.Trash")

    ;; Don't make new frames when opening a new file with Emacs
    (setq ns-pop-up-frames nil)

    ;; set the Fn key as the hyper key
    (setq ns-function-modifier 'hyper)

    ;; Use Command-` to switch between Emacs windows (not frames)
    (bind-key "s-`" 'other-window)

    ;; Use Command-Shift-` to switch Emacs frames in reverse
    (bind-key "s-~" (lambda() () (interactive) (other-window -1)))

    ;; Because of the keybindings above, set one for `other-frame'
    (bind-key "s-1" 'other-frame)

    ;; Fullscreen!
    (setq ns-use-native-fullscreen nil) ; Not Lion style
    (bind-key "<s-return>" 'toggle-frame-fullscreen)

    ;; buffer switching
    (bind-key "s-{" 'previous-buffer)
    (bind-key "s-}" 'next-buffer)

    ;; disable the key that minimizes emacs to the dock because I don't
    ;; minimize my windows
    (global-unset-key (kbd "C-z"))

    ;; Not going to use these commands
    (put 'ns-print-buffer 'disabled t)
    (put 'suspend-frame 'disabled t))
#+END_SRC
* Navigating buffers
Switch to next window with `M-o` instead of `C-x o`.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-o") 'other-window)
#+END_SRC
* EasyPG encryption
#+BEGIN_SRC emacs-lisp
  (use-package epa-file
    :ensure nil
    :config
    (setq
     epa-file-enable t
     epa-file-encrypt-to email-address
     epa-file-select-keys nil
     epa-file-cache-passphrase-for-symmetric-encryption t
     epa-pinentry-mode 'loopback
     epg-gpg-program "gpg"
     epg-debug t)
    :custom
    (epa-file-select-keys 'silent))
#+END_SRC

Defining `epa-pinentry-mode 'loopback` enables the passphrase entering through minibuffer as pointed out by [[https://colinxy.github.io/software-installation/2016/09/24/emacs25-easypg-issue.html][colinxy]].

To encrypt any file with a public key associated for a receiver address, add the following line to the beginning of the file.

#+BEGIN_SRC txt
;; -*- epa-file-encrypt-to: ("me@domain.com") -*-
#+END_SRC

In case of an `.org` file use.

#+BEGIN_SRC txt
# -*- mode:org; epa-file-encrypt-to: ("me@domain.com") -*-
#+END_SRC

The passphrase will be cached depending on the configuration in `~/.gnupg/gpg-agent.conf`.

#+BEGIN_SRC txt
default-cache-ttl 600
max-cache-ttl 7200
#+END_SRC
* Fonts
#+BEGIN_SRC emacs-lisp
  (when (eq system-type 'darwin)
    (set-frame-font "Menlo 14")
                                          ; Use Spotlight to search with M-x locate
    (setq locate-command "mdfind"))
#+END_SRC
* Theme
** Eigengrau
A fork of [[https://github.com/sjrmanning/noctilux-theme][Noctilux]] theme, taken from [[https://github.com/jackrusher/dotemacs/][Jack Rusher's dotemacs]].
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path (concat user-emacs-directory "eigengrau/"))
  (require 'eigengrau-theme)
#+END_SRC
Apply theme without any prompts.
#+BEGIN_SRC emacs-lisp
  (load-theme 'eigengrau t)
#+END_SRC

* Avy
#+BEGIN_SRC emacs-lisp
  (use-package avy
    :ensure t
    :pin melpa-stable
    :bind
    ("C-:" . avy-goto-char))
#+END_SRC
* Cider
#+BEGIN_SRC emacs-lisp
  (use-package cider
    :ensure t
    :pin melpa-stable
    :config
    (setq nrepl-use-ssh-fallback-for-remote-hosts t))
#+END_SRC
* Company
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :defer t
    :config
    (setq
     company-tooltip-limit 10
     company-idle-delay 0.3
     company-echo-delay 0
     company-minimum-prefix-length 1
     company-require-match nil
     company-tooltip-flip-when-above t
     company-transformers '(company-sort-by-occurrence))
    :init (global-company-mode))
#+END_SRC

* Counsel
#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :ensure t
    :pin melpa-stable
    :bind
    ("M-x" . counsel-M-x)
    ("C-x C-f" . counsel-find-file)
    ("C-c g" . counsel-git)
    ("C-x l" . counsel-locate)
    :config
    (define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history))
#+END_SRC
* Csv

[csv-mode](https://elpa.gnu.org/packages/csv-mode.html)
#+BEGIN_SRC emacs-lisp
  (use-package csv-mode
    :ensure t
    :pin gnu
    :init
    (setq csv-separators '("," ";" "\t"))
    (add-to-list 'auto-mode-alist '("\\.[CcTt][Ss][Vv]\\'" . csv-mode)))
#+END_SRC
** Keys
| Binding   | Description                          |
|-----------+--------------------------------------|
| `C-c C-a` | Aligns column width to maximum width |
| `C-c C-u` | Undoes alignment, to source          |
* Docker
#+BEGIN_SRC emacs-lisp
  (use-package docker
    :ensure t
    :bind ("C-c d" . docker))
#+END_SRC
* Exec-path-from-shell
#+BEGIN_SRC emacs-lisp
  (use-package exec-path-from-shell
    :ensure t
    :pin melpa-stable)

  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize))
#+END_SRC
* Expand region
#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :ensure t
    :pin melpa-stable
    :bind ("C-=" . er/expand-region))
#+END_SRC
** Keys
| Binding   | Description |
|-----------+-------------|
| `C-=`     | expand      |
| `C-- C-=` | retract     |
* Indium
[[https://github.com/NicolasPetton/Indium/][Indium]] is a JavaScript environment for Emacs that connects to Chromium or nodejs to provide a REPL, scratch-buffer, stepping debugger.
#+BEGIN_SRC emacs-lisp
  (use-package indium
    :ensure t
    :pin melpa)
#+END_SRC

For a simple project setup follow this [[https://github.com/NicolasPetton/Indium/issues/249#issuecomment-664365115][github comment]].

- `M-x indium-launch` starts a JavaScript process (Chrome or nodejs).
- `M-x indium-connect` to a running runtime.
- `M-x indium-eval-buffer` evals the entire buffer.
- `M-x indium-eval-region` evals current region.

** Keys
| Binding   | Description                       |
|-----------+-----------------------------------|
| `C-x C-e` | evals expression preceding cursor |
| `C-M-x`   | evals innermost function          |
| `C-c M-i` | inspect result of the evaluation  |

* Ivy
#+BEGIN_SRC emacs-lisp
  (use-package ivy
    :ensure t
    :pin melpa-stable
    :config
    (ivy-mode 1)
    (setq
     ivy-count-format " %d/%d "
     ivy-use-virtual-buffers t
     ivy-use-selectable-prompt t
     enable-recursive-minibuffers t
     projectile-completion-system 'ivy
     magit-completing-read-function 'ivy-completing-read)
    :bind
    (:map ivy-minibuffer-map
          ("<return>" . ivy-alt-done)))
#+END_SRC
* Ledger
#+BEGIN_SRC emacs-lisp
  (use-package ledger-mode
    :ensure t
    :pin melpa-stable
    :init
    (setq ledger-reconcile-default-commodity "€"))
#+END_SRC
** Keys
| Binding       | Description                                      |
|---------------+--------------------------------------------------|
| `M-n`         | Next entry                                       |
| `M-p`         | Previous entry                                   |
| `C-c C-s`     | Sort all of the transactions in a region by date |
| `C-c C-r`     | Star reconciliation                              |
| `C-c C-o C-r` | Run report                                       |
* Magit
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t
    :pin melpa-stable
    :bind ("C-x g" . magit-status))
#+END_SRC
* Markdown mode
#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :ensure t
    :pin melpa-stable
    :init
    (add-to-list 'auto-mode-alist '("\\.text\\'" . markdown-mode))
    (add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode))
    (add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode)))
#+END_SRC
* Notmuch
#+BEGIN_SRC emacs-lisp
  (use-package notmuch
    :ensure t
    :pin melpa-stable
    :bind ("C-c m" . notmuch)
    :init
    (setq notmuch-saved-searches
          (quote
           ((:name "inbox" :query "tag:inbox AND -tag:sent" :key "i" :sort-order newest-first)
            (:name "sent" :query "tag:sent" :key "t" :sort-order newest-first)
            (:name "drafts" :query "tag:draft" :key "d")
            (:name "all mail" :query "*" :key "a" :sort-order newest-first))
           ))
    )
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (autoload 'notmuch "notmuch" "notmuch mail" t)
#+END_SRC
** Keys
| Binding | Description                                                           |
|---------+-----------------------------------------------------------------------|
| `C-c m` | Open notmuch globally                                                 |
| `q`     | Kill the current Notmuch buffer and return you to the previous buffer |
| `m`     | New message.                                                          |
| `s`     | Search interface                                                      |
* Olivetti
Minor mode for a nice writing environment that keeps the text in the middle of the window.
#+BEGIN_SRC emacs-lisp
  (use-package olivetti
    :ensure t
    :pin melpa-stable)
#+END_SRC
* Org
Define base directory for all org files.

#+BEGIN_SRC emacs-lisp
  (setq org-directory "~/Dropbox (Personal)/org/")
#+END_SRC

Org files for capturing.

#+BEGIN_SRC emacs-lisp
  (setq
   todo-file (expand-file-name "gtd.org" org-directory)
   media-file (expand-file-name "media.org" org-directory)
   memex-file (expand-file-name "memex.org" org-directory)
   quote-file (expand-file-name "quote.org" org-directory))
#+END_SRC

Org mode's [[https://orgmode.org/manual/Capture-templates.html][caputre templates]] will be automatically filled with a set of [[https://orgmode.org/manual/Template-expansion.html][expansions]].

Changing todo states will invoke the option to take notes and track timestamps depending on [[https://orgmode.org/org.html#Tracking-TODO-state-changes-1][configuration]] using `@` and `!` in keyword definitions.

#+BEGIN_SRC emacs-lisp
  ;; Agenda view
  (setq
   org-agenda-inhibit-startup nil
   org-agenda-show-future-repeats nil
   org-agenda-prefer-last-repeat nil
   org-agenda-start-on-weekday nil
   org-agenda-skip-deadline-if-done t
   org-agenda-skip-scheduled-if-done t
   org-agenda-block-separator "")
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package org
    :ensure t
    :pin org
    :init
    (setq
     ;; Enable syntax highlighting in #+BEGIN_SRC sections.
     org-src-fontify-natively t
     ;; Add log/notebook entries into :LOGBOOK: drawer.
     org-log-into-drawer t
     org-export-coding-system 'utf-8
     org-default-notes-file todo-file
     org-agenda-files '("~/Dropbox (Personal)/org/gtd.org"
                        "~/Dropbox (Personal)/org/gcal-nand.org")
     calendar-week-start-day 1
     org-completion-use-ido t
     ;; Indent text lines that are not headlines are prefixed with
     ;; spaces to vertically align with the headline text.
     org-startup-indented t
     ;; Turn off manual indentation
     org-adapt-indentation nil
     org-indent-indentation-per-level 1
     ;; Deactivate ‘^’ and ‘_’ to be used to indicate super- and subscripts
     org-use-sub-superscripts nil
     ;; Enable refiling of subtree up to 2nd level
     org-refile-targets '((("~/Dropbox (Personal)/org/gtd.org") :maxlevel . 2))
     ;; Use node names instead of their path
     org-refile-use-outline-path nil
     ;; Allow `a.`, `A.`, `a)` and `A)` list style
     org-list-allow-alphabetical t
     ;; Don’t ask every time when executing a code block.
     org-confirm-babel-evaluate nil
     org-src-tab-acts-natively t)
    ;; Sync Google Calendar
    (add-hook 'org-agenda-mode-hook (lambda () (org-gcal-fetch) ))
    ;;(add-hook 'org-capture-after-finalize-hook (lambda () (org-gcal-fetch) ))
    (setq org-capture-templates
          '(("t" "Todo" entry
             (file+headline todo-file "Inbox")
             "* TODO %^{Title}\n%?\n:LOGBOOK:\n- Added: %U\n:END:")
            ("f" "Todo from file" entry
             (file+headline todo-file "Inbox")
             "* TODO %^{Title}\n%?\n:PROPERTIES:\n- File: [[%F][%f]]\n:END:\n:LOGBOOK:\n- Added: %U\n:END:")
            ("r" "Toread article" entry
             (file+headline media-file "Reading")
             "* SOMEDAY %^{Title} :READING:\n:PROPERTIES:\n:SOURCE: %^{Source}\n:END:\n:LOGBOOK:\n- Added: %U\n:END:")
            ("b" "Toread book" entry
             (file+headline media-file "Reading")
             "* SOMEDAY %^{Title} :READING:\n:PROPERTIES:\n:AUTHOR: %^{Author}\n:SOURCE: %^{Source}\n:END:\n:LOGBOOK:\n- Added: %U\n:END:")
            ("m" "Memex" entry
             (file memex-file)
             "* %^{Title}\n%?")
            ("q" "Quote" entry
             (file quote-file)
             "* %^{Quote}\n:PROPERTIES:\:AUTHOR: %^{Author}\:SOURCE: %^{Source}\:PAGE: %^{Page}\:END:\:LOGBOOK:\n- Added: %U\n:END:")
            )
          )
    (setq org-todo-keywords
          '((sequence "TODO(t!)" "NEXT(n!)" "|" "DONE(d@/!)")
            (sequence "WAITING(w@)" "SOMEDAY(s!)" "|")
            (sequence "|" "CANCELLED(c@)"))
          )
    :config
    (setq
     org-display-inline-images t
     org-redisplay-inline-images t
     org-startup-with-inline-images "inlineimages")
    (add-hook 'org-babel-after-execute-hook 'org-display-inline-images 'append)
    :bind
    (("C-c a" . org-agenda)
     ("C-c c" . org-capture)))
#+END_SRC

Since version 9.2 `<s TAB` does not trigger the `#+BEGIN_SRC` [block](https://orgmode.org/manual/Structure-Templates.html#FOOT148). The following fix is taken from an issue [disussion](https://github.com/syl20bnr/spacemacs/issues/11798#issuecomment-456754071).

#+BEGIN_SRC emacs-lisp
  (when (version<= "9.2" (org-version))
    (require 'org-tempo))
#+END_SRC

** Keys

| Binding       | Description                                 |
|---------------+---------------------------------------------|
| `C-c c`       | Open capture menue to select template.      |
| `C-c '`       | Open babel block in separate pop-up buffer. |
| `C-c C-x C-i` | Clock-in on selected task                   |
| `C-c C-x C-o` | Clock-out of selected task                  |
| `C-u C-c C-s` | Unschedule agenda item                      |
| `C-u C-c C-d` | Undealine agenda item                       |
| `r`           | Refresh agenda view                         |
| `C-c C-,`     | Add structural block #+BEGIN_... #+END_...  |

** Snippets

To render todays time tracking stats recorded using clock-in and clock-out.

#+BEGIN_SRC org
  ,#+BEGIN: clocktable :scope file :maxlevel 2 :block today
  ,#+END:
#+END_SRC

* Org Babel
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((dot . t)
     (emacs-lisp . t)
     (js . t)
     (python . t)
     (shell . t)))
#+END_SRC
* Org Crypt
To encrypt sensitive sections in `.org` document I use `org-crypt`. Tag any head line with `:crypt:` and its content will be encrypted when saving the document.

To decrypt the section content place the cursor inside and execute `M-x org-decrypt-entry`.
#+BEGIN_SRC emacs-lisp
  (use-package org-crypt
    :after (org)
    :ensure nil
    :config
    (org-crypt-use-before-save-magic)
    (setq
     org-crypt-key nil
     org-tags-exclude-from-inheritance (quote ("crypt"))))
#+END_SRC
* Org Google Calendar
Integrate Google calendar with org-mode.
#+BEGIN_SRC emacs-lisp
  (use-package org-gcal
    :after (org)
    :ensure t
    :pin melpa
    :config
    (setq
     org-gcal-client-id secrets-org-gcal-client-id
     org-gcal-client-secret secrets-org-gcal-client-secret
     org-gcal-file-alist secrets-org-gcal-file-alist))
#+END_SRC
* Org-roam
An emacs implementation of the [[https://roamresearch.com/][Roam]] knowledge management tool. For more configuration visit the [[https://www.orgroam.com/manual.html][manual]]. General information on the [[https://www.orgroam.com/][official project page]] or [[https://github.com/org-roam/org-roam/][repository]].
#+BEGIN_SRC emacs-lisp
  (use-package org-roam
    :ensure t
    :pin melpa-stable
    :hook
    (after-init . org-roam-mode)
    :config
    (setq
     org-roam-directory "~/Dropbox (Personal)/org/roam/"
     org-roam-db-location "~/Dropbox (Personal)/org/roam/roam.sqlite")
    (setq org-roam-capture-templates
          '(("d" "default" plain (function org-roam--capture-get-point)
             "%?"
             :file-name "memex/${slug}"
             :head "#+TITLE: ${title}\n#+ROAM_KEY: memex.${slug}\n#+ROAM_ALIAS: \n\n"
             :unnarrowed t)
            ("f" "fleet" plain (function org-roam--capture-get-point)
             "%?"
             :file-name "fleets/%<%Y%m%d%H%M%S>-${slug}"
             :head "#+TITLE: ${title}\n\n"
             :unnarrowed t)
            ("m" "media" plain (function org-roam--capture-get-point)
             "%?"
             :file-name "memex/${slug}"
             :head "#+TITLE: ${title}\n#+ROAM_KEY: media.${slug} \n#+ROAM_ALIAS: \n\n#+AUTHOR: \n#+DATE: \n#+TAGS: \n#+URL: \n\n"
             :unnarrowed t)
            ("n" "note" plain (function org-roam--capture-get-point)
             "%?"
             :file-name "notes/%<%Y%m%d%H%M%S>-${slug}"
             :head "#+TITLE: ${title}\n#+ROAM_KEY: note.${slug}\n#+ROAM_ALIAS:\n\n#+AUTHOR: Steffen Fiedler\n#+DATE: %U\n\n"
             :unnarrowed t)
            )
          )
    :bind
    (:map org-roam-mode-map
          (("C-c n l" . org-roam)
           ("C-c n f" . org-roam-find-file)
           ;; No server for rendering set up yet
           ;;("C-c n g" . org-roam-graph)
           )
          :map org-mode-map
          (("C-c n i" . org-roam-insert))
          (("C-c n I" . org-roam-insert-immediate))))
#+END_SRC

** Keys
| Binding   | Description                      |
|-----------+----------------------------------|
| `C-c n f` | Find existing or create new note |
| `C-c n i` | Insert reference                 |
| `C-c n l` | Toggle roam sidebar buffer       |

* Paredit
#+BEGIN_SRC emacs-lisp
  (use-package paredit
    :ensure t
    :pin melpa-stable
    :config
    (add-hook 'prog-mode-hook #'enable-paredit-mode))
#+END_SRC

* Projectile
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :ensure t
    :pin melpa-stable
    :config
    (projectile-global-mode)
    :bind-keymap
    (("C-c p" . projectile-command-map)))
#+END_SRC

** Keys

| Binding   | Description            |
|-----------+------------------------|
| `C-c p p` | Jump to/select project |

* Python
#+BEGIN_SRC emacs-lisp
  (use-package python
    :ensure nil
    :config
    (setq python-shell-interpreter "python3")
    (setenv "PYTHONIOENCODING" "utf-8")
    (setenv "LANG" "en_US.UTF-8"))
#+END_SRC
* Rainbow delimiters
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :pin melpa-stable
    :config
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))
#+END_SRC
* Rainbow mode
Sets background color to strings that match color names, e.g. #0000ff red rgb(100,20,0).
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :pin gnu
    :config
    (add-hook 'prog-mode-hook 'rainbow-mode))
#+END_SRC
* Rcirc
Set IRC user info based on definitions in _secrets.el_.
#+BEGIN_SRC  emacs-lisp
  (setq
   rcirc-default-nick secrets-irc-freenode-user
   rcirc-default-user-name secrets-irc-freenode-user
   rcirc-default-full-name secrets-irc-freenode-user)
#+END_SRC
Minimal configuration. Set freenode as default server, define nickserv auth, and join `irc.freenode.net` on startup.
#+BEGIN_SRC emacs-lisp
  (setq rcirc-authinfo `(("freenode" nickserv ,secrets-irc-freenode-user ,secrets-irc-freenode-pass)))
  (setq rcirc-server-alist
        '(("irc.freenode.net"
           :port 6697
           :encryption tls
           :channels ("#emacs"))))
#+END_SRC
* Restclient
#+BEGIN_SRC emacs-lisp
  (use-package restclient
    :ensure t
    :pin melpa
    :mode (("\\.http\\'" . restclient-mode))
    :bind (:map restclient-mode-map
                ("C-c C-f" . json-mode-beautify)))
#+END_SRC
* SMEX
#+BEGIN_SRC emacs-lisp
  (use-package smex
    :ensure t
    :pin melpa-stable)
#+END_SRC
* Svelte
#+BEGIN_SRC emacs-lisp
  (use-package svelte-mode
    :ensure t
    :pin melpa)
#+END_SRC
* Swiper
#+BEGIN_SRC emacs-lisp
  (use-package swiper
    :ensure t
    :pin melpa-stable
    :bind
    ("C-s" . swiper)
    ("C-c C-r" . ivy-resume))
#+END_SRC
* Which key
[Which key](https://github.com/justbur/emacs-which-key) displays the key bindings following the currently entered incomplete command in a popup.
#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :pin melpa-stable
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))
#+end_src
* Writing
** Single space after periods
#+BEGIN_SRC emacs-lisp
  (setq sentence-end-double-space nil)
#+END_SRC
** Remove dangling whitespaces
When saving delete all trailing whitespaces.
#+BEGIN_SRC emacs-lisp
  (add-hook 'write-file-hooks 'delete-trailing-whitespace)
#+END_SRC
* Customize
#+BEGIN_SRC emacs-lisp
  ;; Customize interface to safe config in separate file
  (setq custom-file (concat user-emacs-directory "custom.el"))
  (load custom-file)
#+END_SRC
